### ISSUE TITLE
Isle of Man, Guernsey, and Jersey

### ISSUE THREAD

**Issue by jnicho02** [osmlab/osm-community-index#333] opened 2020-02-08 13:02 UTC
Official area of coverage for what we call 'United Kingdom' is OSM is the https://en.wikipedia.org/wiki/British_Islands#/media/File:British_Islands.svg 

I'm trying to include the Isle of Man, Guernsey, and Jersey in the OSMUK area, etc.
```json
{
  "id": "uk-localchapter",
  "type": "osm-lc",
  "locationSet": {"include": ["gb", "gg", "je", "im"]},
  ...
}
```
but they don't appear to be creating geojson in /dist/combined.geojson either separately or in a combined gb feature.

Looking at the combined.geojson I think that GB territories are already being included in "iso1A2": "GB"
```json
"members": ["680", "IO", "KY", "AI", "BM", "MS", "DG", "GS", "PN", **"JE"**, "SH", **"GG"**, "TA", "TC", **"IM"**, "FK", "VG", "GI", "AC"],
```
but the GB feature has 5 polygons, not including IM, JE, and GG

Pulling out just the GB Feature from combined.geojson (sorry github issues won't accept .geojson file extension)
[gb.geojson.txt](https://github.com/osmlab/osm-community-index/files/4174187/gb.geojson.txt)

I believe that countryCoder does have geojson for IM, JE, and GG.

**Comment by bhousel** [comment] 2020-02-10 16:15
I looked into this a bit today - It turns out to be this bug in location-conflation, which we use to merge the Country Coder polygons together.  

https://github.com/ideditor/location-conflation/issues/4

**Comment by bhousel** [comment] 2020-02-13 16:19
I think this is fixed with the location-conflation update in df2eb55

Because the `combined.geojson` file in JSDelivr is cached for a while, this won't show up on https://openstreetmap.community/ right away, so I'll leave this open until it's confirmed fixed.

**Comment by bhousel** [comment] 2020-02-16 20:26
> this won't show up on https://openstreetmap.community/ right away, so I'll leave this open until it's confirmed fixed.

Just checked today and it looks good 👍

**Closed by bhousel** 2020-02-16 20:26 UTC

**Comment by jnicho02** [comment] 2020-02-17 07:16
Thank you! :)
